EESTEC/Controllers/LocalEventController.cs
using EESTEC.Data;
using EESTEC.Helpers;
using EESTEC.Interfaces;
using EESTEC.Models;
using EESTEC.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace EESTEC.Controllers
{
    public class LocalEventController : Controller
    {
        private readonly ILocalEventRepository _localEventRepository;
        private readonly IEventFileRepository _eventFileRepository;

        public LocalEventController(ILocalEventRepository localEventRepository, IEventFileRepository eventFileRepository)
        {
            _localEventRepository = localEventRepository;
            _eventFileRepository = eventFileRepository;
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index(int page=1, string search="", int pageSize = 15)
        {
            IEnumerable<LocalEvent> events = await _localEventRepository.GetAll(search);

            //Pagination
            if (page < 1)
                page = 1;
            int itemsCount = events.Count();
            var pager = new Pager(itemsCount, page, pageSize, search);
            int itemSkip = (page - 1) * pageSize;
            var data = events.Skip(itemSkip).Take(pager.PageSize).ToList();
            this.ViewBag.Pager = pager;

            return View(data);
        }
        
        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreateLocalEventViewModel());
        }
        [HttpPost]
        public IActionResult Create(CreateLocalEventViewModel localEventVM, IFormFile[] Files)
        {
            if (!ModelState.IsValid)
                return View(localEventVM);

            foreach(var file in Files)
            {
                if (file.ContentType != "application/pdf")
                {
                    return StatusCode(500, "Prilozi moraju biti u .pdf formatu");
                }
            }

            var localEvent = new LocalEvent
            {
                Date = localEventVM.Date,
                Title = localEventVM.Title,
                EventType = localEventVM.EventType,
                Description = localEventVM.Description,
            };
            localEvent = _localEventRepository.Create(localEvent);

            foreach(var file in Files)
            {
                _eventFileRepository.Create(file, localEvent);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var localEvent = await _localEventRepository.GetById(id);
            if (localEvent == null)
            {
                return View("Error");
            }
            var editVM = new EditLocalEventViewModel
            {
                Title = localEvent.Title,
                Description = localEvent.Description,
                Date = localEvent.Date,
                EventType = localEvent.EventType,
                Files = localEvent.Files,
            };

            foreach(var file in editVM.Files)
            {
                file.Path = "/EventFiles/" + file.Name;
            }
            ViewBag.Id = id;
            return View(editVM);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditLocalEventViewModel eventVM, IFormFile[] Files)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Greška pri uređivanju lokalnog događaja!");
                return View("Edit", eventVM);
            }

            foreach (var file in Files)
            {
                if (file.ContentType != "application/pdf")
                {
                    return StatusCode(500, "Prilozi moraju biti u .pdf formatu");
                }
            }

            var localEvent = await _localEventRepository.GetById(id);
            if (localEvent==null)
                return View("Edit", eventVM);

            foreach (var file in localEvent.Files)
            {
                _eventFileRepository.Delete(file);
            }

            foreach (var file in Files)
            {
                _eventFileRepository.Create(file, localEvent);
            }

            localEvent.Date = eventVM.Date;
            localEvent.EventType = eventVM.EventType;
            localEvent.Title = eventVM.Title;
            localEvent.Description = eventVM.Description;

            _localEventRepository.Update(localEvent);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            var localEvent = await _localEventRepository.GetById(id);
            if (localEvent == null)
                return RedirectToAction("Index");

            foreach(var file in localEvent.Files)
            {
                _eventFileRepository.Delete(file);
            }

            _localEventRepository.Delete(localEvent);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> LocalEventsPartial()
        {
            var localEvents = await _localEventRepository.GetMostRecent();
            return PartialView("~/Views/LocalEvent/_LocalEvents.cshtml", localEvents);
        }

        public async Task<IActionResult> AllLocalEventsPartial()
        {
            var localEvents = await _localEventRepository.GetAll();
            return PartialView("~/Views/LocalEvent/_LocalEvents.cshtml", localEvents);
        }

        public IActionResult Show()
        {
            return View();
        }

        public async Task<IActionResult> Info(int id)
        {
            var LocalEvent = await _localEventRepository.GetById(id);
            return View(LocalEvent);
        }

        public async Task<IActionResult> ShowDocument(int id)
        {
            var file = await _eventFileRepository.GetById(id);
            var stream = new FileStream(file.Path, FileMode.Open);
            return new FileStreamResult(stream, "application/pdf");
        }
    }
}

EESTEC/Controllers/PartnerController.cs
using EESTEC.Interfaces;
using EESTEC.Models;
using EESTEC.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EESTEC.Controllers
{
    public class PartnerController : Controller
    {
        private readonly IPartnerCategoryRepository _partnerCategoryRepository;
        private readonly IPartnerRepository _partnerRepository;
        private readonly IPhotoService _photoService;
        private readonly IDataProtector _dataProtector;
        public PartnerController(IPartnerCategoryRepository partnerCategoryRepository, IPartnerRepository partnerRepository, IPhotoService photoService, IDataProtectionProvider dataProvider, IConfiguration configuration)
        {
            _partnerCategoryRepository = partnerCategoryRepository;
            _partnerRepository = partnerRepository;
            _photoService = photoService;
            _dataProtector = dataProvider.CreateProtector(configuration.GetValue<String>("ProtectionString"));
        }

        private async Task<List<SelectListItem>> GetPartnerCategoriesAsync()
        {
            var list = new List<SelectListItem>();
            var partnerCategories = await _partnerCategoryRepository.GetAllAsync();
            foreach (var category in partnerCategories)
            {
                list.Add(new SelectListItem
                {
                    Text = category.Name,
                    Value = category.Id.ToString(),
                });
            }
            return list;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var partners = await _partnerRepository.GetAllAsync();
            return View(partners);
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var partnerVM = new CreatePartnerViewModel
            {
                PartnerCategoriesSelectList = await GetPartnerCategoriesAsync(),
            };

            return View(partnerVM);
        }
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var partner = await _partnerRepository.GetByIdAsync(id);
            if (partner == null)
                return NotFound();

            string decryptedAccountNumber = (partner.AccountNumber == null) ? "" : _dataProtector.Unprotect(partner.AccountNumber);

            var partnerVM = new EditPartnerViewModel
            {
                Name = partner.Name,
                AccountNumber = decryptedAccountNumber,
                Image = null,
                ImageUrl = partner.Image,
                SelectedCategory = partner.PartnerCategory.Id.ToString(),
                Website = partner.Website,
                PartnerCategoriesSelectList = await GetPartnerCategoriesAsync(),
            };
            foreach (var cat in partnerVM.PartnerCategoriesSelectList)
            {
                if (cat.Value == partnerVM.SelectedCategory)
                {
                    cat.Selected = true;
                    break;
                }
            }
            return View(partnerVM);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreatePartnerViewModel partnerVM)
        {
            if (!ModelState.IsValid)
            {
               partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                return View(partnerVM);
            }

            //Image
            var result = await _photoService.AddPhotoAsync(partnerVM.Image);
            if (result.Error != null)
            {
                ModelState.AddModelError("Photo", "Fotografija nije uspješno učitana");
                partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                return View(partnerVM);
            }

            var partnerCategory = await _partnerCategoryRepository.GetByIdAsync(Int32.Parse(partnerVM.SelectedCategory));
            if (partnerCategory == null)
            {
                partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                return View(partnerVM);
            }

            string? encryptedAccountNumber = (partnerVM.AccountNumber == null) ? null : _dataProtector.Protect(partnerVM.AccountNumber);

            var partner = new Partner
            {
                Name = partnerVM.Name,
                AccountNumber = encryptedAccountNumber,
                PartnerCategory = partnerCategory,
                Website = partnerVM.Website,
                Image = result.Url.ToString(),
            };

            _partnerRepository.Create(partner);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditPartnerViewModel partnerVM)
        {
            var partner = await _partnerRepository.GetByIdAsync(id);
            if (partner == null)
                return NotFound();

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Greška pri uređivanju partnera!");
                partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                partnerVM.ImageUrl = partner.Image;
                return View("Edit", partnerVM);
            }
            

            var partnerCategory = await _partnerCategoryRepository.GetByIdAsync(Int32.Parse(partnerVM.SelectedCategory));
            if (partnerCategory == null)
            {
                partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                return View(partnerVM);
            }

            if (partnerVM.Image != null)
            {
                await _photoService.DeletePhotoAsync(partner.Image);
                var result = await _photoService.AddPhotoAsync(partnerVM.Image);
                if (result.Error != null)
                {
                    ModelState.AddModelError("Photo", "Fotografija nije uspješno učitana");
                    partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                    partnerVM.ImageUrl = partner.Image;
                    return View(partnerVM);
                }
                partnerVM.ImageUrl = result.Url.ToString();

            }

            partner.PartnerCategory = partnerCategory;
            partner.Website = partnerVM.Website;
            partner.AccountNumber = (partnerVM.AccountNumber == null) ? null : _dataProtector.Protect(partnerVM.AccountNumber);
            if (partnerVM.ImageUrl!= null)
                partner.Image = partnerVM.ImageUrl;
            partner.Name = partnerVM.Name;

            _partnerRepository.Update(partner);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            var partner = await _partnerRepository.GetByIdAsync(id);
            if (partner == null)
                return NotFound();
            var result = await _photoService.DeletePhotoAsync(partner.Image);
            if (result.Error != null)
            {
                return RedirectToAction("Index");
            }
            _partnerRepository.Delete(partner);
            return RedirectToAction("Index");
        }
    }
}

EESTEC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="bs">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EESTEC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EESTEC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
            <div class="container-fluid">
                <img class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" src="~/img/logoWhite.png" width="75px" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Naslovna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Novosti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#partners">Partneri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="LocalEvent" asp-action="Show">Lokalni događaji</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Međunarodni događaji</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Kontrolna ploča
                                </a>
                                <ul class="dropdown-menu bg-dark">
                                    <li><a class="dropdown-item text-white" href="#">Novosti</a></li>
                                    <li><a class="dropdown-item text-white" asp-controller="Partner" asp-action="Index">Partneri</a></li>
                                    <li><a class="dropdown-item text-white" href="#">Međunarodni događaji</a></li>
                                    <li><a class="dropdown-item text-white" asp-controller="LocalEvent" asp-action="Index">Lokalni događaji</a></li>
                                    <li><a class="dropdown-item text-white" href="#">Upravni odbori</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Account" asp-action="Logout" class="mr-auto">
                                    <button class="btn nav-link text-white" type="submit">
                                        Odjavi se
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login" method="post">Admin</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - EESTEC LC Sarajevo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EESTEC/Views/Shared/_Pagination.cshtml
@using EESTEC.Helpers
@model Pager;
@{

}
<div class="container">

    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-center">
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="LocalEvent" asp-action="Index" asp-route-search="@Model.SearchParameter" asp-route-page="1" asp-route-pageSize="@Model.PageSize">Prva</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="LocalEvent" asp-action="Index" asp-route-search="@Model.SearchParameter" asp-route-page="@(Model.CurrentPage-1)" asp-route-pageSize="@Model.PageSize">&laquo;</a>
                </li>
            }
            @for (var p = Model.StartPage; p <= Model.EndPage; p++)
            {
                <li class="page-item @(p == Model.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="LocalEvent" asp-action="Index" asp-route-search="@Model.SearchParameter" asp-route-page="@p" asp-route-pageSize="@Model.PageSize">@p</a>
                </li>
            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="LocalEvent" asp-action="Index" asp-route-search="@Model.SearchParameter" asp-route-page="@(Model.CurrentPage+1)" asp-route-pageSize="@Model.PageSize">&raquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="LocalEvent" asp-action="Index" asp-route-search="@Model.SearchParameter" asp-route-page="@(Model.TotalPages)" asp-route-pageSize="@Model.PageSize">Posljednja</a>
                </li>
            }
        </ul>
    }
</div>

EESTEC/Views/Shared/_SortIcon.cshtml
<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" fill="currentColor" viewBox="0 0 320 512" class="w-3 h-3 ms-2 grey">
    <path d="M27.66 224h264.7c24.6 0 36.89-29.78 19.54-47.12l-132.3-136.8c-5.406-5.406-12.47-8.107-19.53-8.107c-7.055 0-14.09 2.701-19.45 8.107L8.119 176.9C-9.229 194.2 3.055 224 27.66 224zM292.3 288H27.66c-24.6 0-36.89 29.77-19.54 47.12l132.5 136.8C145.9 477.3 152.1 480 160 480c7.053 0 14.12-2.703 19.53-8.109l132.3-136.8C329.2 317.8 316.9 288 292.3 288z" />
</svg>