EESTEC/Models/Partner.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace EESTEC.Models
{
    public class Partner
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Image { get; set; }
        public string Website { get; set; }
        public PartnerCategory PartnerCategory { get; set; }
        public string? AccountNumber { get; set; }
    }
}

EESTEC/Controllers/PartnerCategoryController.cs
using EESTEC.Interfaces;
using EESTEC.Models;
using EESTEC.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EESTEC.Controllers
{
    public class PartnerCategoryController : Controller
    {
        private readonly IPartnerCategoryRepository _partnerCategoryRepository;

        public PartnerCategoryController(IPartnerCategoryRepository partnerCategoryRepository)
        {
            _partnerCategoryRepository = partnerCategoryRepository;
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var partnerCategories = await _partnerCategoryRepository.GetAllAsync();
            return View(partnerCategories);
        }

        public async Task<IActionResult> ShowPartial()
        {
            var partners = await _partnerCategoryRepository.GetAllAsync();
            return PartialView("~/Views/PartnerCategory/_PartnersPartial.cshtml", partners);
        }

        [Authorize]
        public IActionResult Create()
        {
            var partnerCategoryVM = new PartnerCategoryViewModel();
            return View(partnerCategoryVM);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(PartnerCategoryViewModel partnerCategoryVM)
        {
            if (!ModelState.IsValid)
                return View(partnerCategoryVM);
            var partnerCategory = new PartnerCategory
            {
                Name = partnerCategoryVM.Name,
                DisplayOrder = partnerCategoryVM.DisplayOrder,
            };
            _partnerCategoryRepository.Create(partnerCategory);
            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var partnerCategory = await _partnerCategoryRepository.GetByIdAsync(id);
            if (partnerCategory == null)
            {
                return View("Error");
            }
            var partnerCategoryVM = new PartnerCategoryViewModel
            {
                Name = partnerCategory.Name,
                DisplayOrder = partnerCategory.DisplayOrder,
            };
            return View(partnerCategoryVM);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, PartnerCategoryViewModel partnerCategoryVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Greška pri uređivanju lokalnog događaja!");
                return View("Edit", partnerCategoryVM);
            }
            var partnerCategory = await _partnerCategoryRepository.GetByIdAsync(id);
            if (partnerCategory == null)
                return View("Edit", partnerCategoryVM);

            partnerCategory.Name = partnerCategoryVM.Name;
            partnerCategory.DisplayOrder = partnerCategoryVM.DisplayOrder;

            _partnerCategoryRepository.Update(partnerCategory);
            return RedirectToAction("Index");
        }
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            var partnerCategory = await _partnerCategoryRepository.GetByIdAsync(id);
            if (partnerCategory == null)
                return RedirectToAction("Index");
            _partnerCategoryRepository.Delete(partnerCategory);
            return RedirectToAction("Index");
        }
    }
}

EESTEC/Controllers/PartnerController.cs
using EESTEC.Interfaces;
using EESTEC.Models;
using EESTEC.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EESTEC.Controllers
{
    public class PartnerController : Controller
    {
        private readonly IPartnerCategoryRepository _partnerCategoryRepository;
        private readonly IPartnerRepository _partnerRepository;
        private readonly IPhotoService _photoService;
        private readonly IDataProtector _dataProtector;
        public PartnerController(IPartnerCategoryRepository partnerCategoryRepository, IPartnerRepository partnerRepository, IPhotoService photoService, IDataProtectionProvider dataProvider, IConfiguration configuration)
        {
            _partnerCategoryRepository = partnerCategoryRepository;
            _partnerRepository = partnerRepository;
            _photoService = photoService;
            _dataProtector = dataProvider.CreateProtector(configuration.GetValue<String>("ProtectionString"));
        }

        private async Task<List<SelectListItem>> GetPartnerCategoriesAsync()
        {
            var list = new List<SelectListItem>();
            var partnerCategories = await _partnerCategoryRepository.GetAllAsync();
            foreach (var category in partnerCategories)
            {
                list.Add(new SelectListItem
                {
                    Text = category.Name,
                    Value = category.Id.ToString(),
                });
            }
            return list;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var partners = await _partnerRepository.GetAllAsync();
            return View(partners);
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var partnerVM = new CreatePartnerViewModel
            {
                PartnerCategoriesSelectList = await GetPartnerCategoriesAsync(),
            };

            return View(partnerVM);
        }
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var partner = await _partnerRepository.GetByIdAsync(id);
            if (partner == null)
                return NotFound();

            string decryptedAccountNumber = (partner.AccountNumber == null) ? "" : _dataProtector.Unprotect(partner.AccountNumber);

            var partnerVM = new EditPartnerViewModel
            {
                Name = partner.Name,
                AccountNumber = decryptedAccountNumber,
                Image = null,
                ImageUrl = partner.Image,
                SelectedCategory = partner.PartnerCategory.Id.ToString(),
                Website = partner.Website,
                PartnerCategoriesSelectList = await GetPartnerCategoriesAsync(),
            };
            foreach (var cat in partnerVM.PartnerCategoriesSelectList)
            {
                if (cat.Value == partnerVM.SelectedCategory)
                {
                    cat.Selected = true;
                    break;
                }
            }
            return View(partnerVM);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreatePartnerViewModel partnerVM)
        {
            if (!ModelState.IsValid)
            {
               partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                return View(partnerVM);
            }

            //Image
            var result = await _photoService.AddPhotoAsync(partnerVM.Image);
            if (result.Error != null)
            {
                ModelState.AddModelError("Photo", "Fotografija nije uspješno učitana");
                partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                return View(partnerVM);
            }

            var partnerCategory = await _partnerCategoryRepository.GetByIdAsync(Int32.Parse(partnerVM.SelectedCategory));
            if (partnerCategory == null)
            {
                partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                return View(partnerVM);
            }

            string? encryptedAccountNumber = (partnerVM.AccountNumber == null) ? null : _dataProtector.Protect(partnerVM.AccountNumber);

            var partner = new Partner
            {
                Name = partnerVM.Name,
                AccountNumber = encryptedAccountNumber,
                PartnerCategory = partnerCategory,
                Website = partnerVM.Website,
                Image = result.Url.ToString(),
            };

            _partnerRepository.Create(partner);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditPartnerViewModel partnerVM)
        {
            var partner = await _partnerRepository.GetByIdAsync(id);
            if (partner == null)
                return NotFound();

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Greška pri uređivanju partnera!");
                partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                partnerVM.ImageUrl = partner.Image;
                return View("Edit", partnerVM);
            }
            

            var partnerCategory = await _partnerCategoryRepository.GetByIdAsync(Int32.Parse(partnerVM.SelectedCategory));
            if (partnerCategory == null)
            {
                partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                return View(partnerVM);
            }

            if (partnerVM.Image != null)
            {
                await _photoService.DeletePhotoAsync(partner.Image);
                var result = await _photoService.AddPhotoAsync(partnerVM.Image);
                if (result.Error != null)
                {
                    ModelState.AddModelError("Photo", "Fotografija nije uspješno učitana");
                    partnerVM.PartnerCategoriesSelectList = await GetPartnerCategoriesAsync();
                    partnerVM.ImageUrl = partner.Image;
                    return View(partnerVM);
                }
                partnerVM.ImageUrl = result.Url.ToString();

            }

            partner.PartnerCategory = partnerCategory;
            partner.Website = partnerVM.Website;
            partner.AccountNumber = (partnerVM.AccountNumber == null) ? null : _dataProtector.Protect(partnerVM.AccountNumber);
            if (partnerVM.ImageUrl!= null)
                partner.Image = partnerVM.ImageUrl;
            partner.Name = partnerVM.Name;

            _partnerRepository.Update(partner);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            var partner = await _partnerRepository.GetByIdAsync(id);
            if (partner == null)
                return NotFound();
            var result = await _photoService.DeletePhotoAsync(partner.Image);
            if (result.Error != null)
            {
                return RedirectToAction("Index");
            }
            _partnerRepository.Delete(partner);
            return RedirectToAction("Index");
        }
    }
}

EESTEC/Views/Partner/Create.cshtml
@using EESTEC.ViewModel
@model CreatePartnerViewModel
@{
    ViewData["Title"] = "Dodavanje partnera";
}

<div class="container mt-3">
    <h1>Kreiranje partnera</h1>
    <form class="mt-2" asp-action="Create" method="post" enctype="multipart/form-data">
        <div class=mb-3>
            <label asp-for="Name" class="form-label">Naziv partnera</label>
            <input asp-for="Name" type="text" class="form-control" id="name" required>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class=mb-3>
            <label asp-for="Website" class="form-label">Link na web stranicu</label>
            <input asp-for="Website" type="text" class="form-control">
            <span asp-validation-for="Website" class="text-danger"></span>
        </div>
        <div class=mb-3>
            <label asp-for="AccountNumber" class="form-label">Broj računa</label>
            <input asp-for="AccountNumber" type="text" class="form-control">
            <span asp-validation-for="AccountNumber" class="text-danger"></span>
        </div>
        <div class=mb-3>
            <div class="row">
                <div class="col-12 col-lg-6">
                    <label asp-for="SelectedCategory" class="form-label">Kategorija partnera</label>
                    <select class="form-select" asp-items="Model.PartnerCategoriesSelectList" asp-for="SelectedCategory">
                    </select>
                    <span asp-validation-for="SelectedCategory" class="text-danger"></span>
                </div>
                <div class="col-12 col-lg-6">
                    <label asp-for="Image" class="form-label">Logotip partnera</label>
                    <input asp-for="Image" type="file" class="form-control" required>
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div>
            <button class="btn btn-primary d-inline mr-2" type="submit">Sačuvaj</button>
            <a class="btn btn-danger d-inline mr-2" type="reset" asp-area="" asp-controller="Partner" asp-action="Index">Odustani</a>
        </div>
    </form>

</div>

EESTEC/Views/Partner/Edit.cshtml
@using EESTEC.ViewModel
@model EditPartnerViewModel

@{
    ViewData["Title"] = "Uređivanje partnera";
}

<div class="container mt-3">
    <h1>Uređivanje partnera</h1>
    <form class="mt-2" asp-action="Edit" method="post" enctype="multipart/form-data">
        <div class=mb-3>
            <label asp-for="Name" class="form-label">Naziv partnera</label>
            <input asp-for="Name" type="text" class="form-control" id="name" required>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class=mb-3>
            <label asp-for="AccountNumber" class="form-label">Broj računa</label>
            <input asp-for="AccountNumber" type="text" class="form-control">
            <span asp-validation-for="AccountNumber" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <div class="col-12 col-lg-6">
                <label asp-for="SelectedCategory" class="form-label">Kategorija partnera</label>
                <select class="form-select" asp-items="Model.PartnerCategoriesSelectList" asp-for="SelectedCategory">
                </select>
                <span asp-validation-for="SelectedCategory" class="text-danger"></span>
            </div>
            <div class="col-12 col-lg-6">
                <label asp-for="Website" class="form-label">Link na web stranicu</label>
                <input asp-for="Website" type="text" class="form-control">
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-lg-6">
                <label asp-for="Image" class="form-label">Logotip partnera</label>
                <input asp-for="Image" type="file" class="form-control">
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="col-12 col-lg-6 d-flex justify-content-center align-content-lg-start">
                <img src="@Model.ImageUrl" alt="Slika" width="100px" />
            </div>
            
        </div>
        <div>
            <button class="btn btn-primary d-inline mr-2" type="submit">Sačuvaj</button>
            <a class="btn btn-danger d-inline mr-2" type="reset" asp-area="" asp-controller="Partner" asp-action="Index">Odustani</a>
        </div>
    </form>

</div>

EESTEC/Views/Partner/Index.cshtml
@model IEnumerable<Partner>
@{
  ViewData["Title"] = "Partneri";
}

<div class="container mt-3">
    <h1>Pregled partnera</h1>

    <div class="d-flex flex-row-reverse">
         <a class="btn btn-outline-dark ms-2" asp-controller="PartnerCategory" asp-action="Index">Upravljanje kategorijama partnera</a>
         <a class="btn btn-outline-dark ms-2" asp-controller="Partner" asp-action="Create">Dodaj partnera</a>
    </div>
    <table class="table mt-4">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Naziv partnera</th>
                <th scope="col">Web stranica</th>
                <th scope="col">Naziv kategorije</th>
                <th scope="col">Opcije</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var @partner in Model)
            {
                <tr>
                    <td class="align-middle" scope="row">@partner.Id</td>
                    <td class="align-middle" scope="row">@partner.Name</td>
                    <td class="align-middle" scope="row">@partner.Website</td>
                    <td class="align-middle" scope="row">@partner.PartnerCategory.Name</td>
                    <td class="align-middle" scope="row">
                        <div>
                            <a class="btn btn-success mr-2 my-1 d-block d-lg-inline" asp-controller="Partner" asp-action="Edit" asp-route-id="@partner.Id">Uredi</a>
                            <form asp-controller="Partner" asp-action="Delete", asp-route-id="@partner.Id" method="post" class="d-lg-inline">
                                <button class="btn btn-danger mr-2 d-block d-lg-inline my-1" type="submit">Izbriši</button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>